background = 0xFF000000
base = 0xFF1A1510
text = 0xFFBA8540
alternate_base = 0xFF12100C
bright_text = 0xFFD49E52
accent = 0xFFBA8540
accent_secondary = 0xFFD49E52
font_family = "Terminus (TTF)"
font_family_monospace = "monospace"
font_size = 11
small_font_size = 10
rounding_large = 8
rounding_small = 4
