background = rgba(000000ff)
base = rgba(1a1510ff)
text = rgba(ba8540ff)
alternate_base = rgba(12100cff)
bright_text = rgba(d49e52ff)
accent = rgba(ba8540ff)
accent_secondary = rgba(d49e52ff)
font_family = Terminus (TTF)
font_family_monospace = monospace
font_size = 11
small_font_size = 10
rounding_large = 8
rounding_small = 4
