background = 0xFF282826
base = 0xFF3C413E
text = 0xFFD8E0DE
alternate_base = 0xFF333833
bright_text = 0xFF89B1A9
accent = 0xFF89B1A9
accent_secondary = 0xFF67837B
font_family = "Terminus (TTF)"
font_family_monospace = "monospace"
font_size = 11
small_font_size = 10
rounding_large = 8
rounding_small = 4
