# Theme: blasphemous-kneeling-stone
colors:
  background_color: '1e1e2e'
  white: 'cdd6f4'
  red: 'f38ba8'
  green: 'a6e3a1'
  yellow: 'f9e2af'
  blue: '89b4fa'
  pink: 'f5c2e7'
  cyan: '94e2d5'
  black: '11111b'
  gray: 'a6adc8'
  darkgray: '45475a'
  darkergray: '313244'

core:
  normal_text: {}
  regular_file: {}
  reset_to_normal: {}

  directory:
    foreground: blue

  symlink:
    foreground: pink

  multi_hard_link: {}

  fifo:
    foreground: black
    background: blue

  socket:
    foreground: black
    background: pink

  door:
    foreground: black
    background: pink

  block_device:
    foreground: cyan
    background: darkergray

  character_device:
    foreground: pink
    background: darkergray

  broken_symlink:
    foreground: black
    background: red

  missing_symlink_target:
    foreground: black
    background: red

  setuid: {}

  setgid: {}

  file_with_capability: {}

  sticky_other_writable: {}

  other_writable: {}

  sticky: {}

  executable_file:
    foreground: red
    font-style: bold

text:
  special:
    foreground: background_color
    background: yellow

  todo:
    font-style: bold

  licenses:
    foreground: gray

  configuration:
    foreground: yellow

  other:
    foreground: yellow

markup:
  foreground: yellow

programming:
  source:
    foreground: green

  tooling:
    foreground: green

    continuous-integration:
      foreground: green

media:
  foreground: pink

office:
  foreground: red

archives:
  foreground: cyan
  font-style: underline

executable:
  foreground: red
  font-style: bold

unimportant:
  foreground: darkgray
