# Theme: blasphemous-mea-culpa
colors:
  background_color: '110f0d'
  white: 'e7eeed'
  red: 'bfcdcc'
  green: '8fc7c7'
  yellow: 'bfcdcc'
  blue: '8fc7c7'
  pink: 'bfcdcc'
  cyan: '8fc7c7'
  black: '0a0908'
  gray: 'a9b6b5'
  darkgray: '413730'
  darkergray: '2a2420'

core:
  normal_text: {}
  regular_file: {}
  reset_to_normal: {}

  directory:
    foreground: blue

  symlink:
    foreground: pink

  multi_hard_link: {}

  fifo:
    foreground: black
    background: blue

  socket:
    foreground: black
    background: pink

  door:
    foreground: black
    background: pink

  block_device:
    foreground: cyan
    background: darkergray

  character_device:
    foreground: pink
    background: darkergray

  broken_symlink:
    foreground: black
    background: red

  missing_symlink_target:
    foreground: black
    background: red

  setuid: {}

  setgid: {}

  file_with_capability: {}

  sticky_other_writable: {}

  other_writable: {}

  sticky: {}

  executable_file:
    foreground: red
    font-style: bold

text:
  special:
    foreground: background_color
    background: yellow

  todo:
    font-style: bold

  licenses:
    foreground: gray

  configuration:
    foreground: yellow

  other:
    foreground: yellow

markup:
  foreground: yellow

programming:
  source:
    foreground: green

  tooling:
    foreground: green

    continuous-integration:
      foreground: green

media:
  foreground: pink

office:
  foreground: red

archives:
  foreground: cyan
  font-style: underline

executable:
  foreground: red
  font-style: bold

unimportant:
  foreground: darkgray
