# Theme: blasphemous-II-main-menu
colors:
  background_color: '111316'
  white: 'dfe5ea'
  red: '996548'
  green: '627d8a'
  yellow: '996548'
  blue: '627d8a'
  pink: '996548'
  cyan: '627d8a'
  black: '0a0c0e'
  gray: '8d979f'
  darkgray: '262933'
  darkergray: '201f27'

core:
  normal_text: {}
  regular_file: {}
  reset_to_normal: {}

  directory:
    foreground: blue

  symlink:
    foreground: pink

  multi_hard_link: {}

  fifo:
    foreground: black
    background: blue

  socket:
    foreground: black
    background: pink

  door:
    foreground: black
    background: pink

  block_device:
    foreground: cyan
    background: darkergray

  character_device:
    foreground: pink
    background: darkergray

  broken_symlink:
    foreground: black
    background: red

  missing_symlink_target:
    foreground: black
    background: red

  setuid: {}

  setgid: {}

  file_with_capability: {}

  sticky_other_writable: {}

  other_writable: {}

  sticky: {}

  executable_file:
    foreground: red
    font-style: bold

text:
  special:
    foreground: background_color
    background: yellow

  todo:
    font-style: bold

  licenses:
    foreground: gray

  configuration:
    foreground: yellow

  other:
    foreground: yellow

markup:
  foreground: yellow

programming:
  source:
    foreground: green

  tooling:
    foreground: green

    continuous-integration:
      foreground: green

media:
  foreground: pink

office:
  foreground: red

archives:
  foreground: cyan
  font-style: underline

executable:
  foreground: red
  font-style: bold

unimportant:
  foreground: darkgray
