background = rgba(2F3541ff)
base = rgba(3B4352ff)
text = rgba(A6B8C4ff)
alternate_base = rgba(20242Eff)
bright_text = rgba(7492A7ff)
accent = rgba(3B4352ff)
accent_secondary = rgba(7492A7ff)
font_family = Terminus (TTF)
font_family_monospace = monospace
font_size = 11
small_font_size = 10
rounding_large = 0
rounding_small = 0
