background = 0xFF141E1E
base = 0xFF354A4A
text = 0xFFD8E0DE
alternate_base = 0xFF223333
bright_text = 0xFF5A8A8A
accent = 0xFF5A8A8A
accent_secondary = 0xFFB0C0BE
font_family = "Terminus (TTF)"
font_family_monospace = "monospace"
font_size = 11
small_font_size = 10
rounding_large = 8
rounding_small = 4
