background = 0xFF171E26
base = 0xFF222B36
text = 0xFFFFFFFF
alternate_base = 0xFF1A2029
bright_text = 0xFFA0C3BC
accent = 0xFFA0C3BC
accent_secondary = 0xFFBCD5D0
font_family = "Terminus (TTF)"
font_family_monospace = "monospace"
font_size = 11
small_font_size = 10
rounding_large = 8
rounding_small = 4
