background = rgba(171e26ff)
base = rgba(222b36ff)
text = rgba(ffffffff)
alternate_base = rgba(1a2029ff)
bright_text = rgba(a0c3bcff)
accent = rgba(a0c3bcff)
accent_secondary = rgba(bcd5d0ff)
font_family = Terminus (TTF)
font_family_monospace = monospace
font_size = 11
small_font_size = 10
rounding_large = 8
rounding_small = 4
