background = rgba(181818ff)
base = rgba(222222ff)
text = rgba(a2a2a2ff)
alternate_base = rgba(141414ff)
bright_text = rgba(757575ff)
accent = rgba(595959ff)
accent_secondary = rgba(757575ff)
font_family = Terminus (TTF)
font_family_monospace = monospace
font_size = 11
small_font_size = 10
rounding_large = 0
rounding_small = 0
