background = 0xFF111316
base = 0xFF262933
text = 0xFFDFE5EA
alternate_base = 0xFF201F27
bright_text = 0xFF996548
accent = 0xFF996548
accent_secondary = 0xFF627D8A
font_family = "Terminus (TTF)"
font_family_monospace = "monospace"
font_size = 11
small_font_size = 10
rounding_large = 8
rounding_small = 4
