background = 0xFF1E1E2E
base = 0xFF45475A
text = 0xFFCDD6F4
alternate_base = 0xFF313344
bright_text = 0xFFCBA6F7
accent = 0xFFCBA6F7
accent_secondary = 0xFFF5C2E7
font_family = "Terminus (TTF)"
font_family_monospace = "monospace"
font_size = 11
small_font_size = 10
rounding_large = 8
rounding_small = 4
