background = rgba(110f0dff)
base = rgba(413730ff)
text = rgba(e7eeedff)
alternate_base = rgba(2a2420ff)
bright_text = rgba(8fc7c7ff)
accent = rgba(8fc7c7ff)
accent_secondary = rgba(bfcdccff)
font_family = Terminus (TTF)
font_family_monospace = monospace
font_size = 11
small_font_size = 10
rounding_large = 8
rounding_small = 4
