background = 0xFF110F0D
base = 0xFF413730
text = 0xFFE7EEED
alternate_base = 0xFF2A2420
bright_text = 0xFF8FC7C7
accent = 0xFF8FC7C7
accent_secondary = 0xFFBFCDCC
font_family = "Terminus (TTF)"
font_family_monospace = "monospace"
font_size = 11
small_font_size = 10
rounding_large = 8
rounding_small = 4
