# theme: blasphemous-II-main-menu
background              #111316
foreground              #DFE5EA
cursor                  #DFE5EA
cursor_text_color       #111316
selection_foreground    #DFE5EA
selection_background    #333647
active_tab_background   #262933
active_tab_foreground   #996548
inactive_tab_background #1D1D23
inactive_tab_foreground #718994

background_opacity 0.90
