# theme: blasphemous-mea-culpa

code_syntax_highlight = "catppuccin-macchiato"

full_screen_fg = "#e7eeed"
full_screen_bg = "#110f0d"
gradient_color = ["#8fc7c7", "#b78355"]

file_panel_fg = "#e7eeed"
file_panel_bg = "#110f0d"
file_panel_border = "#413730"
file_panel_border_active = "#8fc7c7"
file_panel_top_directory_icon = "#b78355"
file_panel_top_path = "#8fc7c7"
file_panel_item_selected_fg = "#e7eeed"
file_panel_item_selected_bg = "#413730"

footer_fg = "#e7eeed"
footer_bg = "#110f0d"
footer_border = "#413730"
footer_border_active = "#8fc7c7"

sidebar_fg = "#e7eeed"
sidebar_bg = "#110f0d"
sidebar_title = "#b78355"
sidebar_border = "#413730"
sidebar_border_active = "#8fc7c7"
sidebar_item_selected_fg = "#e7eeed"
sidebar_item_selected_bg = "#413730"
sidebar_divider = "#413730"

modal_fg = "#e7eeed"
modal_bg = "#110f0d"
modal_border_active = "#8fc7c7"
modal_cancel_fg = "#110f0d"
modal_cancel_bg = "#b78355"
modal_confirm_fg = "#110f0d"
modal_confirm_bg = "#8fc7c7"

help_menu_hotkey = "#8fc7c7"
help_menu_title = "#b78355"

cursor = "#e7eeed"
correct = "#8fc7c7"
error = "#b78355"
hint = "#8fc7c7"
cancel = "#b78355"
