background = rgba(000000ff)
base = rgba(1a1a1aff)
text = rgba(e0e0e0ff)
alternate_base = rgba(111111ff)
bright_text = rgba(e0e0e0ff)
accent = rgba(e0e0e0ff)
accent_secondary = rgba(ffffffbb)
font_family = Terminus (TTF)
font_family_monospace = monospace
font_size = 11
small_font_size = 10
rounding_large = 8
rounding_small = 4
