background = 0xFF000000
base = 0xFF1A1A1A
text = 0xFFE0E0E0
alternate_base = 0xFF111111
bright_text = 0xFFE0E0E0
accent = 0xFFE0E0E0
accent_secondary = 0xBBFFFFFF
font_family = "Terminus (TTF)"
font_family_monospace = "monospace"
font_size = 11
small_font_size = 10
rounding_large = 8
rounding_small = 4
