background = 0xFF45342F
base = 0xFF5A443E
text = 0xFFD4CCB0
alternate_base = 0xFF3D2E2A
bright_text = 0xFFC8A863
accent = 0xFFC8A863
accent_secondary = 0xFFA09670
font_family = "Terminus (TTF)"
font_family_monospace = "monospace"
font_size = 11
small_font_size = 10
rounding_large = 8
rounding_small = 4
