background = rgba(45342fff)
base = rgba(5a443eff)
text = rgba(d4ccb0ff)
alternate_base = rgba(3d2e2aff)
bright_text = rgba(c8a863ff)
accent = rgba(c8a863ff)
accent_secondary = rgba(a09670ff)
font_family = Terminus (TTF)
font_family_monospace = monospace
font_size = 11
small_font_size = 10
rounding_large = 8
rounding_small = 4
