background = 0xFFD9D1D2
base = 0xFFC0B8BA
text = 0xFF2A282C
alternate_base = 0xFFE3DDDE
bright_text = 0xFF3D2932
accent = 0xFF3D2932
accent_secondary = 0xFF7C7578
font_family = "Terminus (TTF)"
font_family_monospace = "monospace"
font_size = 11
small_font_size = 10
rounding_large = 8
rounding_small = 4
