background = rgba(d9d1d2ff)
base = rgba(c0b8baff)
text = rgba(2a282cff)
alternate_base = rgba(e3dddeff)
bright_text = rgba(3d2932ff)
accent = rgba(3d2932ff)
accent_secondary = rgba(7c7578ff)
font_family = Terminus (TTF)
font_family_monospace = monospace
font_size = 11
small_font_size = 10
rounding_large = 8
rounding_small = 4
