# ===================================
#  Hyprlock 0.9+
#  File: ~/.config/hypr/hyprlock.conf
#  Theme: blasphemous-II-main-menu
# ===================================

background {
  monitor =
  path = ~/.cache/hypr/hyprlock-wallpaper-blur.png
  blur_size = 3
  blur_passes = 3
  brightness = 0.55
}

input-field {
  monitor =
  size = 280, 45
  outline_thickness = 1
  outer_color = rgb(996548)
  inner_color = rgb(111316)
  font_color = rgb(DFE5EA)
  placeholder_text = <i>  Password</i>
  position = 0, -100
  halign = center
  valign = center
  rounding = 6
}

shape {
  monitor =
  size = 320, 150
  color = rgba(17, 19, 22, 0.68)
  rounding = 12
  position = 0, 83
  halign = center
  valign = center
}

label {
  monitor =
  text = cmd[update:1000] echo "$(date +"%H:%M")"
  color = rgba(223, 229, 234, 0.82)
  font_size = 64
  font_family = JetBrainsMono Nerd Font
  position = 0, 100
  halign = center
  valign = center
}

label {
    monitor =
    text = cmd[update:60000] date +"%a, %d %B"
    color = rgba(176, 191, 203, 0.78)
    font_size = 18
    font_family = JetBrainsMono Nerd Font
    position = 0, 40
    halign = center
    valign = center
}
