background = 0xFF181818
base = 0xFF303030
text = 0xFFFFFFFF
alternate_base = 0xFF222222
bright_text = 0xFF3AA99F
accent = 0xFF3AA99F
accent_secondary = 0xFF86E0D9
font_family = "Terminus (TTF)"
font_family_monospace = "monospace"
font_size = 11
small_font_size = 10
rounding_large = 8
rounding_small = 4
